# Generated by Django 4.2.7 on 2023-12-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='prix',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='nom',
        ),
        migrations.DeleteModel(
            name='EquipmentSubcategory',
        ),
    ]
