# Generated by Django 4.2.7 on 2023-12-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_rename_prix_equipment_price_remove_equipment_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='produit',
            new_name='equipement',
        ),
    ]
