# Generated by Django 4.2.7 on 2023-12-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_rename_produit_article_equipement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='location',
            new_name='address',
        ),
    ]
