# Generated by Django 4.2.7 on 2023-12-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0007_remove_equipment_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rental_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
