# Generated by Django 4.2.7 on 2023-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0008_equipment_is_rented_equipment_rental_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='payment_mode',
            field=models.CharField(choices=[('day', 'Par jour'), ('month', 'Par mois'), ('week', 'Par semaine')], default='month', max_length=10),
        ),
    ]
