# Generated by Django 4.2.7 on 2023-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0009_equipment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rental_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
