# Generated by Django 4.2.7 on 2023-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0011_equipment_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='payment_mode',
            field=models.CharField(choices=[('jour', 'Par jour'), ('mois', 'Par mois'), ('semaine', 'Par semaine')], default='mois', max_length=10),
        ),
    ]
