# Generated by Django 4.2.7 on 2023-12-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0012_alter_equipment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
