# Generated by Django 4.2.7 on 2023-12-13 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agriculture', '0014_panierlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_commande', models.BooleanField(default=False)),
                ('date_commande', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.IntegerField(default=1)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='panierlocation',
            name='articles',
            field=models.ManyToManyField(to='agriculture.articlelocation'),
        ),
    ]
