# Generated by Django 4.2.7 on 2023-12-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0015_articlelocation_alter_panierlocation_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='quantite',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='articlelocation',
            old_name='quantite',
            new_name='quantity',
        ),
    ]
