# Generated by Django 4.2.7 on 2023-12-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0016_rename_quantite_article_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='quantity',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='articlelocation',
            old_name='quantity',
            new_name='quantite',
        ),
    ]
