# Generated by Django 4.2.7 on 2023-12-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, default='photos/comptes/my_profile.png', null=True, upload_to='comptes/utilisateurs'),
        ),
    ]
